name: Build And Deploy Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/void-linux/void-glibc-full:latest
      options: --privileged

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          path: source

      - name: Install dependencies
        run: |
          mkdir -p /etc/xbps.d
          cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/

          xbps-install -Sy \
            xbps \
            git \
            bash \
            shadow \
            sudo \
            xtools \
            66-devel \
            python3

      - name: Create builder
        run: |
          useradd -m -G xbuilder builder
          chown -R builder:builder "$GITHUB_WORKSPACE/source"

      - name: Build packages
        working-directory: source
        run: |
          sudo -Eu builder \
            python3 -m scripts.packager \
            --workspace /tmp/work \
            --target "$GITHUB_WORKSPACE/source/out" \
            --arch x86_64 aarch64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: source/out
